{% set name = "skprogs" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dftbplus/skprogs/archive/refs/tags/{{ version }}.tar.gz
  sha256: a16cc91cfa702b2e40b61bbe218fd43d9225469c6e90b56ab04b89838916f9bf
  patches:
    - no-python.patch

build:
  number: 0
  skip: true  # [win or osx]

requirements:
  build:
    - {{ compiler('fortran') }}
    - cmake
    - ninja
    - python
    - numpy
    - scipy
  host:
    - libxc
    - libblas
    - liblapack

test:
  commands:
    - test -f $PREFIX/bin/slateratom
    - $PREFIX/bin/slateratom --version
    - test -f $PREFIX/bin/sktwocnt
    - $PREFIX/bin/sktwocnt --version

about:
  home: https://github.com/dftbplus/skprogs
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: |
    Package containing programs to generate Slater-Koster files for the DFTB-method
  dev_url: https://github.com/dftbplus/skprogs

extra:
  recipe-maintainers:
    - aradi
    - awvwgk
    - vanderhe
