{% set name = "skprogs" %}
{% set version = "0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dftbplus/skprogs/archive/refs/heads/main.zip
  sha256: da48e77a5d3b68334e0195211273c61372a410f5a4500eee56e8ed46d2ba5186
  patches:
    - no-python.patch

build:
  number: 0
  skip: true  # [win or osx]

requirements:
  build:
    - {{ compiler('fortran') }}
    - cmake
    - ninja
    - python
    - numpy
    - scipy
  host:
    - libxc
    - libblas
    - liblapack

test:
  commands:
    - test -f $PREFIX/bin/slateratom
    - $PREFIX/bin/slateratom --version
    - test -f $PREFIX/bin/sktwocnt
    - sktwocnt --version

about:
  home: https://github.com/dftbplus/skprogs
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: |
    Package containing programs to generate Slater-Koster files for the DFTB-method
  dev_url: https://github.com/dftbplus/skprogs

extra:
  recipe-maintainers:
    - aradi
    - awvwgk
    - vanderhe
