{% set name = "skprogs" %}
{% set version = "0.4" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://github.com/dftbplus/skprogs/archive/refs/tags/{{ version }}.tar.gz
  url: https://github.com/vanderhe/skprogs/archive/refs/heads/sktwocntMpi.zip
  sha256: 67ba1f9e3035924be4667c8a22d8f01a8af21280cd909347250de12ef076c66f
  patches:
    - no-python.patch

{% if mpi == "nompi" %}
{% set build = build + 100 %}
{% endif %}
build:
  number: {{ build }}
  skip: true  # [win or osx]

  {% if mpi != "nompi" %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}

  {% if mpi != "nompi" %}
  run_exports:
    - {{ name }} * {{ mpi_prefix }}_*
  {% endif %}

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
    - python
    - numpy
    - scipy
  host:
    - {{ mpi }}  # [mpi != "nompi"]
    - mpifx * mpi_{{ mpi }}_*  # [mpi != "nompi"]
    - libxc
    - libblas
    - liblapack
  run:
    - {{ mpi }}  # [mpi != "nompi"]
    - {{ pin_compatible('mpifx', max_pin='x.x') }} mpi_{{ mpi }}_*  # [mpi != "nompi"]

test:
  commands:
    - export OMPI_MCA_plm=isolated OMPI_MCA_btl_vader_single_copy_mechanism=none OMPI_MCA_rmaps_base_oversubscribe=yes  # [mpi == "openmpi"]
    - test -f $PREFIX/bin/slateratom
    - $PREFIX/bin/slateratom --version
    - test -f $PREFIX/bin/sktwocnt
    - $PREFIX/bin/sktwocnt --version  # [mpi == "nompi"]
    - mpiexec $PREFIX/bin/sktwocnt --version  # [mpi != "nompi"]

about:
  home: https://github.com/dftbplus/skprogs
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: |
    Package containing programs to generate Slater-Koster files for the DFTB-method
  dev_url: https://github.com/dftbplus/skprogs

extra:
  recipe-maintainers:
    - aradi
    - awvwgk
    - vanderhe
